export const sidebarItems = [
    {
        id: '1',
        title: 'Dashboard',
        permission: '',
        icon: '/assets/svg/dashboard.svg',
        link: '/dashboard',
    },
    {
        id: '2',
        title: 'Tags',
        permission: 'tags',
        icon: '/assets/svg/dashboard.svg',
        link: '/tags',
    },
    {
        id: '3',
        title: 'Investigation Summary',
        permission: 'investigation_summary',
        icon: '/assets/svg/dashboard.svg',
        link: '/investigation_summary',
    },
    {
        id: '4',
        title: 'Page URL List',
        permission: 'page_url_list',
        icon: '/assets/svg/dashboard.svg',
        link: '/page_url_list',
    },
    {
        id: '5',
        title: 'Page Sect List',
        permission: 'page_sect_list',
        icon: '/assets/svg/dashboard.svg',
        link: '/page_sect_list',
    },
    {
        id: '6',
        title: 'Tracker List',
        permission: 'tracker_list',
        icon: '/assets/svg/dashboard.svg',
        link: '/tracker_list',
    },
    {
        id: '7',
        title: 'Vendor List',
        permission: 'vendor_list',
        icon: '/assets/svg/dashboard.svg',
        link: '/vendor_list',
    },
]
